name: ragstack-generator
services:
- name: api
  source_dir: /
  github:
    repo: Amarnathss/RAGStackGen
    branch: main
  run_command: cd dist && npm start
  build_command: npm run build && cd dist && npm install --production
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: DATABASE_URL
    value: ${DATABASE_URL}
    type: SECRET
  - key: GROQ_API_KEY
    value: ${GROQ_API_KEY}
    type: SECRET
  - key: GITHUB_TOKEN
    value: ${GITHUB_TOKEN}
    type: SECRET
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    type: SECRET
  health_check:
    http_path: /api/health
